project:
  type: website

website:
  title: "Sarah Zeller"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv/cv.pdf
        text: CV
      - href: blog/index.qmd
        text: Blog
        

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

