project:
  type: website
  render:
    - "*.qmd"
    - "!cv/cv.qmd"

website:
  title: "Sarah Zeller"
  favicon: assets/favicon-data.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv/cv.pdf
        text: CV
      - href: blog/index.qmd
        text: Blog
        

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

